service: aws-rough-functions

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}
  environment:
    FX_ENDPOINT: "https://api.aoikujira.com/kawase/json/usd"
    BUCKET_NAME: ${file(./serverless.env.yml):BUCKET_NAME}
    SNS_PRICE_UPDATE_ARN: ${file(./serverless.env.yml):SNS_PRICE_UPDATE_ARN}
    SLACK_WEBHOOK_URL: ${file(./serverless.env.yml):SLACK_WEBHOOK_URL}
    CIRCLE_API_KEY: ${file(./serverless.env.yml):CIRCLE_API_KEY}
    CIRCLE_DEPLOY_ENDPOINT: ${file(./serverless.env.yml):CIRCLE_DEPLOY_ENDPOINT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "pricing:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"
    - Effect: Allow
      Action:
        - "cloudfront:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - "sns:Publish"
      Resource:
        - ${self:provider.environment.SNS_PRICE_UPDATE_ARN}
plugins:
  - serverless-domain-manager
custom:
  defaultProfile: default
  customDomain:
    domainName: aws-api.noplan.cc
    basePath: ''
    stage: production
    createRoute53Record: true
functions:
  fx:
    handler: functions/batch/fx/handler.main
    memorySize: 512
    timeout: 15
    events:
      - schedule: cron(0 1 * * ? *)
  price:
    handler: functions/batch/price/handler.main
    memorySize: 512
    timeout: 15
    events:
      - sns: ${self:provider.environment.SNS_PRICE_UPDATE_ARN}
  getZ:
    handler: functions/api/z/get.main
    events:
      - http:
          path: /z/{hash}
          method: get
          cors: true
  postZ:
    handler: functions/api/z/post.main
    events:
      - http:
          path: /z
          method: post
          cors: true