service: aws-rough-batch

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}
  environment:
    BUCKET_NAME: ${self:custom.BUCKET_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "pricing:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.BUCKET_NAME}/*"
custom:
  defaultProfile: default
  BUCKET_NAME: ${file(./serverless.env.yml):BUCKET_NAME} 
functions:
  price:
    handler: handler.price
    events:
      - schedule: cron(0 1 * * ? *)
  fx:
    handler: handler.fx
    events:
      - schedule: cron(0 1 * * ? *)