service: aws-rough-functions

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}
  environment:
    FX_ENDPOINT: "https://api.exchangeratesapi.io/latest?base=USD"
    BUCKET_NAME: ${file(./serverless.env.yml):BUCKET_NAME}
    SNS_PRICE_UPDATE_ARN: ${file(./serverless.env.yml):SNS_PRICE_UPDATE_ARN}
    SLACK_WEBHOOK_URL: ${file(./serverless.env.yml):SLACK_WEBHOOK_URL}
    CIRCLE_API_TOKEN: ${file(./serverless.env.yml):CIRCLE_API_TOKEN}
    CIRCLE_BUILD_ENDPOINT: ${file(./serverless.env.yml):CIRCLE_BUILD_ENDPOINT}
  apiGateway:
    minimumCompressionSize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "pricing:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"
    - Effect: Allow
      Action:
        - "cloudfront:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - "sns:Publish"
      Resource:
        - ${self:provider.environment.SNS_PRICE_UPDATE_ARN}
plugins:
  - serverless-domain-manager
  - serverless-webpack
custom:
  defaultProfile: default
  stage: "${opt:stage, self:provider.stage}"
  customDomain:
    domainName: ${self:custom.${self:custom.stage}.domain}
    basePath: ''
    stage: ${self:custom.stage}
    createRoute53Record: true
  dev:
    domain: dev-aws-api.noplan.cc
    priceScheduleEnabled: false
  production:
    domain: aws-api.noplan.cc
    priceScheduleEnabled: true
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  fx:
    handler: src/functions/batch/fx.main
    memorySize: 512
    timeout: 300
    events:
      - schedule:
          rate: cron(0 1 * * ? *)
          enables: ${self:custom.${self:custom.stage}.priceScheduleEnabled}
  price:
    handler: src/functions/batch/price.main
    memorySize: 512
    timeout: 300
    events:
      - sns: ${self:provider.environment.SNS_PRICE_UPDATE_ARN}
  getZ:
    handler: src/functions/api/z/get.main
    events:
      - http:
          path: /z/{hash}
          method: get
          cors: true
  postZ:
    handler: src/functions/api/z/post.main
    events:
      - http:
          path: /z
          method: post
          cors: true