service: aws-rough-batch

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}
  environment:
    BUCKET_NAME: ${file(./serverless.env.yml):BUCKET_NAME}
    CF_DIST_ID: ${file(./serverless.env.yml):CF_DIST_ID}
    SLACK_WEBHOOK_URL: ${file(./serverless.env.yml):SLACK_WEBHOOK_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "pricing:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"
    - Effect: Allow
      Action:
        - "cloudfront:*"
      Resource: "*"
custom:
  defaultProfile: default
functions:
  price:
    handler: functions/price/handler.main
    memorySize: 512
    timeout: 15
    events:
      - schedule: cron(0 1 * * ? *)