service: aws-rough-batch

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}
  environment:
    FX_ENDPOINT: "https://api.aoikujira.com/kawase/json/usd"
    BUCKET_NAME: ${file(./serverless.env.yml):BUCKET_NAME}
    CF_DIST_ID: ${file(./serverless.env.yml):CF_DIST_ID}
    SNS_PRICE_UPDATE_ARN: ${file(./serverless.env.yml):SNS_PRICE_UPDATE_ARN}
    SNS_PRICE_VALIDATION_ARN: ${file(./serverless.env.yml):SNS_PRICE_VALIDATION_ARN}
    SLACK_WEBHOOK_URL: ${file(./serverless.env.yml):SLACK_WEBHOOK_URL}
    PRODUCTION_VALIDATE_ORIGIN: ${file(./serverless.env.yml):PRODUCTION_VALIDATE_ORIGIN}
    LOCAL_PRICE_PATH: ${file(./serverless.env.yml):LOCAL_PRICE_PATH, ''}
    LOCAL_FX_PATH: ${file(./serverless.env.yml):LOCAL_FX_PATH, ''}
    LOCAL_VALIDATE_ORIGIN: ${file(./serverless.env.yml):LOCAL_VALIDATE_ORIGIN, ''}
    LOCAL_CHROME_PATH: ${file(./serverless.env.yml):LOCAL_CHROME_PATH, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "pricing:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"
    - Effect: Allow
      Action:
        - "cloudfront:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - "sns:Publish"
      Resource:
        - ${self:provider.environment.SNS_PRICE_UPDATE_ARN}
        - ${self:provider.environment.SNS_PRICE_VALIDATION_ARN}
custom:
  defaultProfile: default
functions:
  fx:
    handler: functions/fx/handler.main
    memorySize: 512
    timeout: 15
    events:
      - schedule: cron(0 1 * * ? *)
  price:
    handler: functions/price/handler.main
    memorySize: 512
    timeout: 15
    events:
      - sns: ${self:provider.environment.SNS_PRICE_UPDATE_ARN}
  validate:
    handler: functions/validate/handler.main
    memorySize: 2048
    timeout: 20
    events:
      - sns: ${self:provider.environment.SNS_PRICE_VALIDATION_ARN}