version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10-jessie-browsers
    steps:
      - checkout
      - run:
          name: Create AWS Credentials
          command: |
            mkdir ~/.aws &&
            echo "[default]" > ~/.aws/credentials &&
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >>  ~/.aws/credentials &&
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >>  ~/.aws/credentials
      - run:
          name: Create Env File
          command: echo $SERVERLESS_ENV | base64 --decode > serverless.env.yml
      - restore_cache:
          name: Restore npm package
          keys:
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          name: Save npm package
          key: node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test
      - run: npm run deploy:production
      - run: npm run invoke:production fx

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master